// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rubenheeren_aspnet_core_react.Data;

#nullable disable

namespace rubenheeren_aspnet_core_react.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230301100517_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("rubenheeren_aspnet_core_react.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "This is Content 1",
                            CreatedTime = new DateTime(2023, 3, 1, 11, 5, 17, 370, DateTimeKind.Local).AddTicks(6621),
                            Title = "Title for post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "This is Content 2",
                            CreatedTime = new DateTime(2023, 3, 1, 11, 5, 17, 370, DateTimeKind.Local).AddTicks(6668),
                            Title = "Title for post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is Content 3",
                            CreatedTime = new DateTime(2023, 3, 1, 11, 5, 17, 370, DateTimeKind.Local).AddTicks(6671),
                            Title = "Title for post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is Content 4",
                            CreatedTime = new DateTime(2023, 3, 1, 11, 5, 17, 370, DateTimeKind.Local).AddTicks(6673),
                            Title = "Title for post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is Content 5",
                            CreatedTime = new DateTime(2023, 3, 1, 11, 5, 17, 370, DateTimeKind.Local).AddTicks(6675),
                            Title = "Title for post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "This is Content 6",
                            CreatedTime = new DateTime(2023, 3, 1, 11, 5, 17, 370, DateTimeKind.Local).AddTicks(6677),
                            Title = "Title for post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
